### ISSUE TITLE
Error while using inline-css

### ISSUE THREAD

**Issue by tracec0d3** [jonkemp/flat-util#3]
After the new update I got error the below mentioned error
TypeError: isArrayLike is not a function
    at module.exports (/usr/src/app/node_modules/for-each-plus/index.js:16:6)
    at flatten (/usr/src/app/node_modules/flat-util/index.js:7:2)
    at module.exports (/usr/src/app/node_modules/flat-util/index.js:26:38)
    at module.exports (/usr/src/app/node_modules/pick-util/index.js:47:10)
    at module.exports (/usr/src/app/node_modules/list-stylesheets/index.js:46:8)
    at module.exports (/usr/src/app/node_modules/extract-css/index.js:9:18)
    at /usr/src/app/node_modules/inline-css/lib/inlineContent.js:12:9
    at new Promise (<anonymous>)
    at inlineContent (/usr/src/app/node_modules/inline-css/lib/inlineContent.js:5:12)
    at /usr/src/app/node_modules/inline-css/index.js:26:5

We using inline css, and they using flat-util package internally

**Comment by jonkemp** [comment]
v1.1.3 just pushed should fix the issue.
